name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    #- name: configure
    #  run: ./configure

    - name: Apt update and upgrade
      run: sudo apt-get update && sudo apt-get upgrade
      
    - name: Apt install deps
      run: sudo apt install libssl-dev libcurl-dev upx -y

    - name: Make programs
      run: make

    #- name: Run check
    #  run: make check

    #- name: Run distcheck
    #  run: make distcheck
